import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { collectBoundedLocalText, type CollectorDependencies, type ControlState, type RevisionState } from "../src/integration/bounded-local-collector.js";
import type { ForgeCommandMissionAdmission } from "../src/integration/forge-command-adapter.js";

const fixture = (name: string): any => JSON.parse(readFileSync(`fixtures/bounded-collector/${name}`, "utf8"));

const COMMIT = "17f775573985e2f9834c983107bd5fede4886e3a";
const TREE = "52294232d873c592345a157107a5f05246e5fe27";
const admission = (overrides: Partial<ForgeCommandMissionAdmission> = {}): ForgeCommandMissionAdmission => ({
  schemaVersion:"forgesentinel.forge-command-adapter.mission.v1",missionId:"mis_cp4c",runId:"run_cp4c",intentId:"int_cp4c",authorizationId:"auth_cp4c",issuerId:"forge_command",nonce:"nonce_cp4c",issuedAt:"2026-09-14T12:00:00.000Z",notBefore:"2026-09-14T12:00:00.000Z",expiresAt:"2026-09-14T12:05:00.000Z",freshnessDeadline:"2026-09-14T12:04:00.000Z",target:{registryId:"reg_forgesentinel",repository:"Boswell-Digital-Solutions/forgesentinel",registryState:"admitted",commitSha:COMMIT,treeSha:TREE},procedure:{id:"eas_governed_observation",major:1},lanes:["security","truthfulness","accuracy"],caps:{wallTimeMs:60000,evidenceBytes:2097152,fileCount:250,readOps:300,retries:1},identities:{analyzerId:"analyzer_cp4c",analyzerStateToken:"state_analyzer_cp4c",verifierId:"verifier_cp4c",verifierStateToken:"state_verifier_cp4c"},redactionPolicyId:"redaction_cp4c",stop:{channelId:"stop_cp4c",state:"active"},...overrides
});
let control: ControlState = "active"; let revision: RevisionState = {commitSha:COMMIT,treeSha:TREE}; let clock="2026-09-14T12:00:01.000Z";
const deps = (extra: Partial<CollectorDependencies> = {}): CollectorDependencies => ({now:()=>clock,control:()=>control,revision:()=>revision,...extra});
const sandbox = (): string => { const root=mkdtempSync(join(tmpdir(),"fs-cp4c-")); for(const p of ["doc/system","docs/sentinel","src","test","fixtures"]) mkdirSync(join(root,p),{recursive:true}); return root; };
const put=(root:string,path:string,data:string|Uint8Array):void=>writeFileSync(join(root,path),data);
const run=(root:string,paths:string[],a=admission(),d=deps())=>collectBoundedLocalText(root,a,{paths},d);
test.afterEach(()=>{control="active";revision={commitSha:COMMIT,treeSha:TREE};clock="2026-09-14T12:00:01.000Z";});

test("collects deterministic safe text with digest and zero effects",()=>{const r=sandbox();try{put(r,"src/a.ts","export const a = 1;\n");const a=run(r,["src/a.ts"]),b=run(r,["src/a.ts"]);assert.equal(a.state,"COMPLETED");assert.deepEqual(a,b);assert.equal(a.acceptedEffects,0);assert.match(a.observations[0]!.digest,/^sha256:/);}finally{rmSync(r,{recursive:true,force:true});}});
test("valid three-path fixture completes",()=>{const r=sandbox();try{const f=fixture("manifest.valid.json");for(const p of f.paths)put(r,p,"safe synthetic text");assert.equal(run(r,f.paths).observations.length,3);}finally{rmSync(r,{recursive:true,force:true});}});
test("relative root is blocked before reads",()=>assert.equal(run("relative",["src/a.ts"]).reason,"root_not_absolute"));
test("missing root is blocked before reads",()=>assert.equal(run("/definitely/missing/cp4c",["src/a.ts"]).reason,"root_unavailable"));
test("empty manifest is blocked",()=>{const r=sandbox();try{assert.equal(run(r,[]).reason,"empty_manifest");}finally{rmSync(r,{recursive:true,force:true});}});
test("duplicate manifest path is blocked",()=>{const r=sandbox();try{assert.equal(run(r,["src/a.ts","src/a.ts"]).reason,"duplicate_path");}finally{rmSync(r,{recursive:true,force:true});}});
test("path traversal fixture is blocked",()=>{const r=sandbox();try{const f=fixture("case.path-escape.json");assert.equal(run(r,f.paths).reason,f.expected);}finally{rmSync(r,{recursive:true,force:true});}});
test("absolute path is blocked",()=>{const r=sandbox();try{assert.equal(run(r,["/etc/passwd"]).reason,"unsafe_path");}finally{rmSync(r,{recursive:true,force:true});}});
test("unlisted root is blocked",()=>{const r=sandbox();try{put(r,"README.md","safe");assert.equal(run(r,["README.md"]).reason,"unsafe_path");}finally{rmSync(r,{recursive:true,force:true});}});
test("backslash path is blocked",()=>{const r=sandbox();try{assert.equal(run(r,["src\\a.ts"]).reason,"unsafe_path");}finally{rmSync(r,{recursive:true,force:true});}});
test("symlink fixture is rejected",()=>{const r=sandbox(),outside=mkdtempSync(join(tmpdir(),"fs-out-"));try{put(outside,"x.txt","safe");symlinkSync(join(outside,"x.txt"),join(r,"src/link.txt"));const f=fixture("case.symlink.json");assert.equal(run(r,f.paths).reason,f.expected);}finally{rmSync(r,{recursive:true,force:true});rmSync(outside,{recursive:true,force:true});}});
test("directory is rejected as unsafe file type",()=>{const r=sandbox();try{mkdirSync(join(r,"src/dir"));assert.equal(run(r,["src/dir"]).reason,"unsafe_file_type");}finally{rmSync(r,{recursive:true,force:true});}});
test("secret-shaped fixture is blocked and content is not returned",()=>{const r=sandbox();try{const f=fixture("case.secret.json");put(r,f.paths[0],f.content);const x=run(r,f.paths);assert.equal(x.reason,f.expected);assert.equal(x.observations.length,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("private key marker is blocked",()=>{const r=sandbox();try{put(r,"src/key.txt","-----BEGIN PRIVATE KEY-----\nsynthetic");assert.equal(run(r,["src/key.txt"]).reason,"secret_shaped_content");}finally{rmSync(r,{recursive:true,force:true});}});
test("NUL binary fixture is blocked",()=>{const r=sandbox();try{const f=fixture("case.binary.json");put(r,f.paths[0],Uint8Array.from(f.bytes));assert.equal(run(r,f.paths).reason,f.expected);}finally{rmSync(r,{recursive:true,force:true});}});
test("malformed UTF-8 fixture is blocked",()=>{const r=sandbox();try{const f=fixture("case.malformed-utf8.json");put(r,f.paths[0],Uint8Array.from(f.bytes));assert.equal(run(r,f.paths).reason,f.expected);}finally{rmSync(r,{recursive:true,force:true});}});
test("revision drift blocks before opening",()=>{const r=sandbox();try{put(r,"src/example.ts","safe");const f=fixture("case.revision-drift.json");revision=f.revision;const x=run(r,f.paths);assert.equal(x.reason,f.expected);assert.equal(x.usage.filesOpened,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("stop blocks before opening",()=>{const r=sandbox();try{put(r,"src/example.ts","safe");const f=fixture("case.stop.json");control=f.control;const x=run(r,f.paths);assert.equal(x.reason,f.expected);assert.equal(x.usage.filesOpened,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("revocation halts",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");control="revoked";assert.equal(run(r,["src/a.ts"]).reason,"control_revoked");}finally{rmSync(r,{recursive:true,force:true});}});
test("channel loss fails",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");control="channel_lost";assert.equal(run(r,["src/a.ts"]).state,"FAILED");}finally{rmSync(r,{recursive:true,force:true});}});
test("expiry blocks before opening at equality",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");clock="2026-09-14T12:05:00.000Z";const x=run(r,["src/a.ts"]);assert.equal(x.state,"BLOCKED");assert.equal(x.reason,"invalid_admission");assert.equal(x.usage.filesOpened,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("file-count cap stops before overshoot",()=>{const r=sandbox();try{put(r,"src/a.ts","a");put(r,"src/b.ts","b");const a=admission({caps:{...admission().caps,fileCount:1}});const x=run(r,["src/a.ts","src/b.ts"],a);assert.equal(x.reason,"file_count_cap");assert.equal(x.usage.filesOpened,1);}finally{rmSync(r,{recursive:true,force:true});}});
test("read-op cap stops before overshoot",()=>{const r=sandbox();try{put(r,"src/a.ts","a");put(r,"src/b.ts","b");const a=admission({caps:{...admission().caps,readOps:1}});const x=run(r,["src/a.ts","src/b.ts"],a);assert.equal(x.reason,"read_ops_cap");assert.equal(x.usage.readOps,1);}finally{rmSync(r,{recursive:true,force:true});}});
test("evidence cap stops before opening oversized file",()=>{const r=sandbox();try{put(r,"src/a.ts","12345");const a=admission({caps:{...admission().caps,evidenceBytes:4}});const x=run(r,["src/a.ts"],a);assert.equal(x.reason,"evidence_byte_cap");assert.equal(x.usage.filesOpened,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("wall-time cap stops before opening next file",()=>{const r=sandbox();try{put(r,"src/a.ts","a");put(r,"src/b.ts","b");let calls=0;const d=deps({now:()=>{calls++;return calls<3?"2026-09-14T12:00:01.000Z":"2026-09-14T12:01:02.000Z";}});const x=run(r,["src/a.ts","src/b.ts"],admission(),d);assert.equal(x.reason,"wall_time_cap");assert.equal(x.usage.filesOpened,1);}finally{rmSync(r,{recursive:true,force:true});}});
test("revision change before finalization halts completed reads",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");let calls=0;const d=deps({revision:()=>{calls++;return calls===1?revision:{commitSha:"0".repeat(40),treeSha:"0".repeat(40)};}});const x=run(r,["src/a.ts"],admission(),d);assert.equal(x.reason,"revision_drift");assert.equal(x.observations.length,1);}finally{rmSync(r,{recursive:true,force:true});}});
test("stop before finalization prevents completion",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");let calls=0;const d=deps({control:()=>{calls++;return calls===1?"active":"stopped";}});const x=run(r,["src/a.ts"],admission(),d);assert.equal(x.state,"HALTED");assert.equal(x.reason,"control_stopped");}finally{rmSync(r,{recursive:true,force:true});}});
test("file mutation during read is detected",()=>{const r=sandbox();try{put(r,"src/a.ts","safe");const d=deps({afterOpen:()=>put(r,"src/a.ts","changed and longer")});const x=run(r,["src/a.ts"],admission(),d);assert.equal(x.reason,"file_changed_during_read");assert.equal(x.observations.length,0);}finally{rmSync(r,{recursive:true,force:true});}});
test("missing file is a visible failed gap",()=>{const r=sandbox();try{const x=run(r,["src/missing.ts"]);assert.equal(x.state,"FAILED");assert.equal(x.gaps[0]?.path,"src/missing.ts");}finally{rmSync(r,{recursive:true,force:true});}});
