import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { admissionIdentity, observationReturnHash, validateForgeCommandMissionAdmission, validateForgeCommandObservationReturn, type ForgeCommandMissionAdmission, type ForgeCommandObservationReturn } from "../src/integration/forge-command-adapter.js";

const dir = "fixtures/forge-command-adapter";
const json = (name: string): any => JSON.parse(readFileSync(`${dir}/${name}`, "utf8"));
const validAdmission = (): ForgeCommandMissionAdmission => json("admission.valid.json");
const validReturn = (): ForgeCommandObservationReturn => json("return.valid.json");
const mutate = (base: any, patch: any): any => ({ ...base, ...patch });

test("CP4B admission fixture is valid inside its time window", () => assert.equal(validateForgeCommandMissionAdmission(validAdmission(), "2026-09-14T12:00:30.000Z").ok, true));
test("CP4B admission identity is deterministic", () => assert.equal(admissionIdentity(validAdmission()), admissionIdentity(json("admission.valid.json"))));
test("missing authority fails closed", () => { const v:any=validAdmission(); delete v.authorizationId; assert.equal(validateForgeCommandMissionAdmission(v).ok, false); });
test("unknown admission major fails closed", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(), {schemaVersion:"forgesentinel.forge-command-adapter.mission.v2"})).issues.some(x=>x.code==="unknown_major")));
test("unknown admission field fails closed", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(), {authorityGuess:true})).issues.some(x=>x.code==="unknown_field")));
test("not-yet-valid authority fails closed", () => assert.ok(validateForgeCommandMissionAdmission(validAdmission(), "2026-09-14T11:59:59.000Z").issues.some(x=>x.code==="not_yet_valid")));
test("expired authority fails closed at equality", () => assert.ok(validateForgeCommandMissionAdmission(validAdmission(), "2026-09-14T12:05:00.000Z").issues.some(x=>x.code==="expired")));
test("freshness fails closed at equality", () => { const f=json("admission.stale.json"); assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),f.mutation),f.validateAt).issues.some(x=>x.code===f.expectedCode)); });
test("revoked stop fixture fails closed", () => { const f=json("admission.revoked-stop.json"); assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),f.mutation)).issues.some(x=>x.code===f.expectedCode)); });
test("procedure substitution fails closed", () => { const f=json("admission.substituted.json"); assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),f.mutation)).issues.some(x=>x.code===f.expectedCode)); });
test("all over-ceiling caps are rejected", () => { const f=json("admission.unsafe-cap.json"); assert.equal(validateForgeCommandMissionAdmission(mutate(validAdmission(),f.mutation)).issues.filter(x=>x.code===f.expectedCode).length,5); });
test("analyzer and verifier identity collision is rejected", () => { const f=json("admission.independence.json"); assert.equal(validateForgeCommandMissionAdmission(mutate(validAdmission(),f.mutation)).issues.filter(x=>x.code===f.expectedCode).length,2); });
test("unknown Registry target is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{target:{...validAdmission().target,registryState:"unknown"}})).issues.some(x=>x.code==="target_not_admitted")));
test("conflicted Registry target is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{target:{...validAdmission().target,registryState:"conflicted"}})).issues.some(x=>x.code==="target_not_admitted")));
test("local path cannot substitute for repository identity", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{target:{...validAdmission().target,repository:"/tmp/forgesentinel"}})).issues.some(x=>x.path==="target.repository")));
test("commit substitution with short SHA is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{target:{...validAdmission().target,commitSha:"9439edf"}})).issues.some(x=>x.path==="target.commitSha")));
test("lane omission is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{lanes:["security","accuracy"]})).issues.some(x=>x.code==="lane_set_mismatch")));
test("lane duplication is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{lanes:["security","security","accuracy"]})).issues.some(x=>x.code==="lane_set_mismatch")));
test("freshness may not outlive authority", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{freshnessDeadline:"2026-09-14T12:06:00.000Z"})).issues.some(x=>x.code==="time_order")));
test("zero retry cap is valid", () => assert.equal(validateForgeCommandMissionAdmission(mutate(validAdmission(),{caps:{...validAdmission().caps,retries:0}})).ok,true));
test("zero file cap is rejected", () => assert.ok(validateForgeCommandMissionAdmission(mutate(validAdmission(),{caps:{...validAdmission().caps,fileCount:0}})).issues.some(x=>x.code==="cap_out_of_range")));
test("valid return digest verifies", () => assert.equal(validateForgeCommandObservationReturn(validReturn()).ok,true));
test("return hash helper reproduces fixture", () => { const v:any=validReturn(); const {integrity,...body}=v; assert.equal(observationReturnHash(body),integrity.hash); });
test("tampered return is rejected", () => { const f=json("return.tampered.json"); assert.ok(validateForgeCommandObservationReturn(mutate(validReturn(),f.mutation)).issues.some(x=>x.code===f.expectedCode)); });
test("unknown return major fails closed", () => assert.ok(validateForgeCommandObservationReturn(mutate(validReturn(),{schemaVersion:"forgesentinel.forge-command-adapter.return.v2"})).issues.some(x=>x.code==="unknown_major")));
test("unknown return field fails closed", () => assert.ok(validateForgeCommandObservationReturn(mutate(validReturn(),{canonical:true})).issues.some(x=>x.code==="unknown_field")));
test("nonzero accepted effects are rejected", () => assert.ok(validateForgeCommandObservationReturn(mutate(validReturn(),{acceptedEffects:1})).issues.some(x=>x.code==="effect_violation")));
test("any redaction leak is rejected", () => assert.ok(validateForgeCommandObservationReturn(mutate(validReturn(),{redactionLeaks:1})).issues.some(x=>x.code==="redaction_failure")));
test("usage above every CP4 ceiling is rejected", () => { const v=mutate(validReturn(),{usage:{wallTimeMs:60001,evidenceBytes:2097153,filesOpened:251,readOps:301,retries:2}}); assert.equal(validateForgeCommandObservationReturn(v).issues.filter(x=>x.code==="cap_out_of_range").length,5); });
test("coverage gaps cannot claim health", () => { const v=mutate(validReturn(),{reason:"healthy",coverage:{requiredLanes:["security","truthfulness","accuracy"],inspectedLanes:["security"],gaps:[{lane:"truthfulness",reason:"collector_failure"}]}}); assert.ok(validateForgeCommandObservationReturn(v).issues.some(x=>x.code==="false_health")); });
test("blocked return with zero usage remains valid when rehashed", () => { const v:any=mutate(validReturn(),{state:"BLOCKED",reason:"missing_authority",usage:{wallTimeMs:0,evidenceBytes:0,filesOpened:0,readOps:0,retries:0},coverage:{requiredLanes:["accuracy","security","truthfulness"],inspectedLanes:[],gaps:[{lane:"*",reason:"missing_authority"}]}}); const {integrity:_,...body}=v; v.integrity={hash:observationReturnHash(body)}; assert.equal(validateForgeCommandObservationReturn(v).ok,true); });
test("parent receipt lineage is accepted only as an explicit known field", () => { const v:any=mutate(validReturn(),{parentReceiptId:"mrcpt_parent_001"}); const {integrity:_,...body}=v; v.integrity={hash:observationReturnHash(body)}; assert.equal(validateForgeCommandObservationReturn(v).ok,true); });
